name: Notify
on:
  workflow_dispatch:
jobs:
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: https://discord.com/api/webhooks/1022189972830306395/lXCQt0OuS44MvPraWk2_bauJz7dBmYKk6b1ocE5L7TVAlweWQh6iNP1E3GOjQ-uGBbjk
      uses: Ilshidur/action-discord@master
      with:
        args: 'The project has been deployed.'
   
     
